In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/kaggle/input/nasa-battery-dataset/cleaned_dataset/metadata.csv")
df1 = pd.read_csv("/kaggle/input/nasa-battery-dataset/cleaned_dataset/data/00001.csv")

In [3]:
df

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
0,discharge,[2010. 7. 21. 15. 0. ...,4,B0047,0,1,00001.csv,1.6743047446975208,NaN,NaN
1,impedance,[2010. 7. 21. 16. 53. ...,24,B0047,1,2,00002.csv,NaN,0.05605783343888099,0.20097016584458333
2,charge,[2010. 7. 21. 17. 25. ...,4,B0047,2,3,00003.csv,NaN,NaN,NaN
3,impedance,[2010 7 21 20 31 5],24,B0047,3,4,00004.csv,NaN,0.05319185850921101,0.16473399914864734
4,discharge,[2.0100e+03 7.0000e+00 2.1000e+01 2.1000e+01 2...,4,B0047,4,5,00005.csv,1.5243662105099023,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7560,impedance,[2010. 9. 30. 7. 36. ...,24,B0055,247,7561,07561.csv,NaN,0.0968087979207628,0.15489738203707232
7561,discharge,[2010. 9. 30. 8. 8. ...,4,B0055,248,7562,07562.csv,1.0201379996149256,NaN,NaN
7562,charge,[2010. 9. 30. 8. 48. 54.25],4,B0055,249,7563,07563.csv,NaN,NaN,NaN
7563,discharge,[2010. 9. 30. 11. 50. ...,4,B0055,250,7564,07564.csv,0.9907591663373165,NaN,NaN
7564,charge,[2010. 9. 30. 12. 31. ...,4,B0055,251,7565,07565.csv,NaN,NaN,NaN

In [4]:
df1

,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time
0,4.246711,0.000252,6.212696,0.0002,0.000,0.000
1,4.246764,-0.001411,6.234019,0.0002,4.262,9.360
2,4.039277,-0.995093,6.250255,1.0000,3.465,23.281
3,4.019506,-0.996731,6.302176,1.0000,3.451,36.406
4,4.004763,-0.992845,6.361645,1.0000,3.438,49.625
...,...,...,...,...,...,...
485,3.303251,-0.001760,9.662331,0.0004,0.000,6382.063
486,3.310303,-0.000756,9.390489,0.0002,0.000,6395.547
487,3.317351,-0.003318,9.137008,0.0002,0.000,6409.063
488,3.323387,-0.002291,8.972806,0.0002,0.000,6422.625
489,3.329356,-0.001326,8.756381,0.0002,0.000,6436.141

In [5]:
import os
import pandas as pd
import numpy as np

# ======================================================
# 1) Your SoC function (unchanged)
# ======================================================

def compute_soc_precise(
    df: pd.DataFrame,
    time_col: str = "Time",
    current_col: str = "Current_measured",
    voltage_col: str = "Voltage_measured",
    current_noise_threshold: float = 1e-3,
    known_capacity_Ah: float = None,
):
    """
    Estimate State of Charge (SoC) from BMS data using coulomb counting.

    Columns used:
      - Time (s)
      - Current_measured (A), negative during discharge, positive during charge
      - Voltage_measured (V) used only for optional anchoring / sanity

    Returns:
        df_out: DataFrame with extra columns:
            - delta_t      : time step in seconds
            - I_clean      : current with noise removed
            - delta_Ah     : incremental ΔAh (+ for charging, - for discharging)
            - cum_Ah       : cumulative Ah change (relative to first sample)
            - SoC_raw      : SoC from coulomb counting before anchoring
            - SoC          : SoC after anchoring to [0,1]
            - SoC_percent  : SoC in %
        capacity_Ah: capacity used for normalization (known or estimated)
    """

    df = df.copy()
    df = df.sort_values(time_col).reset_index(drop=True)

    # 1) Time step Δt
    df["delta_t"] = df[time_col].diff().fillna(0.0)  # seconds

    # 2) Noise filter on current
    I = df[current_col].values.astype(float)
    I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
    df["I_clean"] = I_clean

    # 3) Convert current*dt to Ah
    df["delta_Ah"] = df["I_clean"] * df["delta_t"] / 3600.0

    # 4) Cumulative Ah from the start of the file
    df["cum_Ah"] = df["delta_Ah"].cumsum()

    # 5) Estimate capacity if not given (from discharge part)
    if known_capacity_Ah is None:
        discharge_Ah = (
            (df["I_clean"].clip(upper=0).abs() * df["delta_t"] / 3600.0).sum()
        )
        capacity_Ah = discharge_Ah
    else:
        capacity_Ah = float(known_capacity_Ah)

    # 6) Raw SoC from coulomb counting.
    df["SoC_raw"] = 1.0 + df["cum_Ah"] / capacity_Ah

    # 7) Anchor SoC between 0 and 1 over this file
    soc0 = df["SoC_raw"].iloc[0]
    socN = df["SoC_raw"].iloc[-1]

    if soc0 != socN:
        df["SoC"] = (df["SoC_raw"] - socN) / (soc0 - socN)  # rescale to [0,1]
    else:
        df["SoC"] = df["SoC_raw"]

    df["SoC"] = df["SoC"].clip(0.0, 1.0)
    df["SoC_percent"] = df["SoC"] * 100.0

    return df, capacity_Ah


# ======================================================
# 2) Run SoC computation on all 7565 CSV files
# ======================================================

# Paths – adjust to your setup
METADATA_PATH = "/kaggle/input/nasa-battery-dataset/cleaned_dataset/metadata.csv"
DATA_DIR      = "/kaggle/input/nasa-battery-dataset/cleaned_dataset/data"
OUTPUT_DIR    = "/kaggle/working/data_with_soc"   # new folder for CSVs with SoC

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load metadata so we know which filenames to process
metadata = pd.read_csv(METADATA_PATH)

# Optional: if the filename column is not string type, convert it
metadata["filename"] = metadata["filename"].astype(str)

# Process each file listed in metadata
for i, fname in enumerate(metadata["filename"], start=1):
    in_path = os.path.join(DATA_DIR, fname)
    out_path = os.path.join(OUTPUT_DIR, fname)

    if not os.path.isfile(in_path):
        print(f"[WARN] {fname}: file not found, skipping.")
        continue

    try:
        df = pd.read_csv(in_path)
    except Exception as e:
        print(f"[WARN] {fname}: error reading file ({e}), skipping.")
        continue

    # Make sure required columns exist
    required_cols = ["Time", "Current_measured", "Voltage_measured"]
    if not all(col in df.columns for col in required_cols):
        print(f"[WARN] {fname}: missing required columns {required_cols}, skipping.")
        continue

    # Compute SoC for this file
    df_soc, cap_Ah = compute_soc_precise(
        df,
        time_col="Time",
        current_col="Current_measured",
        voltage_col="Voltage_measured",
    )

    # df_soc already contains a "SoC" column (and SoC_percent, etc.)
    # Save to new CSV in OUTPUT_DIR
    df_soc.to_csv(out_path, index=False)

    # Progress log every 100 files
    if i % 100 == 0:
        print(f"Processed {i} files...")

print("Done. All CSVs with SoC are in:", OUTPUT_DIR)

[WARN] 00002.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00004.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00014.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00016.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00018.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00020.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00030.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00032.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00034.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00036.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00046.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00048.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00058.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00060.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00070.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00072.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00082.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00084.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00086.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00088.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00098.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00100.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00110.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00112.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00122.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00124.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00134.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00136.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00138.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00140.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00150.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00152.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00154.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00156.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00166.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00168.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00170.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00172.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00182.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00184.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00186.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00188.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00198.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00200.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00202.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00204.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00214.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00216.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00218.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00220.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00230.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00232.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00242.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00244.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00254.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00256.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00266.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00268.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00270.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00272.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00282.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00284.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00294.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00296.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 300 files...

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00306.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00308.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00318.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00320.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00322.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00324.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00334.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00336.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00338.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00340.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00350.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00352.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00354.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00356.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00366.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00368.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00370.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00372.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00382.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00384.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00386.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00388.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00398.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00400.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00402.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00404.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00414.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00416.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00426.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00428.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00438.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00440.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00450.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00452.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00454.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00456.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00466.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00468.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00478.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00480.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00490.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00492.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 500 files...
[WARN] 00502.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00504.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00506.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00508.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00518.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00520.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00522.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00524.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00534.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00536.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00538.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00540.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00550.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00552.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00554.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00556.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00566.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00568.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00570.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00572.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00582.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00584.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00586.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00588.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00598.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00600.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00610.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00612.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00622.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00624.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00634.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00636.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00638.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00640.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00650.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00652.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00662.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00664.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00674.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00676.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00686.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00688.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00690.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00692.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 700 files...
[WARN] 00702.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00704.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00706.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00708.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00718.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00720.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00722.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00724.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00734.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00736.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00738.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00748.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00750.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00760.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00762.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00772.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00774.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00784.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00786.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00788.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00790.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00800.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00802.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00812.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00814.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00824.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00826.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00836.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00838.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00840.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00842.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00851.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00861.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00863.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00873.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00875.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00885.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00887.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00897.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00899.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 900 files...
[WARN] 00901.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00903.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00913.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00915.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00925.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00927.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00937.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00939.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00949.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00951.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00953.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00955.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00965.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00967.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00977.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00979.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 00989.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 00991.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1000 files...
[WARN] 01001.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01003.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01012.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01022.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01024.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01034.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01036.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01046.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01048.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01058.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01060.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01070.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01072.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01082.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01084.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01094.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01096.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1100 files...
[WARN] 01106.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01108.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01110.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01112.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01122.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01124.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01126.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01128.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01138.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01140.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01142.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01144.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01154.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01156.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01158.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01160.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01170.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01172.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01182.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01184.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01194.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01196.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1200 files...
[WARN] 01206.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01208.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01210.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01212.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01222.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01224.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01226.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01228.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01232.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01234.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01244.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01246.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01248.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01250.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01260.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01262.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01264.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01266.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01276.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01278.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01280.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01282.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01292.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01294.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1300 files...
[WARN] 01304.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01306.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01316.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01318.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01328.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01330.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01332.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01334.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01344.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01346.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01348.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01350.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01353.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01363.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01365.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01375.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01377.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01387.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01389.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01399.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1400 files...
[WARN] 01401.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01411.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01413.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01423.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01425.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01435.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01437.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01447.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01449.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01450.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01452.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01462.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01464.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01466.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01468.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01477.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01479.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01481.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01483.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01493.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01495.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01497.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01499.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1500 files...
[WARN] 01509.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01511.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01512.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01514.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01524.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01526.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01528.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01531.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01541.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01543.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01553.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01555.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01565.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01567.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01577.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01579.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01581.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01583.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01593.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01595.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1600 files...
[WARN] 01605.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01607.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01617.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01619.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01629.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01631.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01633.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01635.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01644.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01654.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01656.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01666.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01668.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01678.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01680.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01690.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01692.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01694.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01696.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1700 files...
[WARN] 01706.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01708.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01718.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01720.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01730.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01732.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01742.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01744.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01746.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01748.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01758.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01760.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01770.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01772.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01782.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01784.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01794.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01796.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1800 files...

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01806.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01808.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01818.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01820.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01830.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01832.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01842.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01844.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01854.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01856.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01858.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01860.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01870.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01872.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01882.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01884.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01894.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01896.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 1900 files...
[WARN] 01906.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01908.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01910.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01912.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 01918.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01920.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01930.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01932.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01942.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01944.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01954.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01956.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01966.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01968.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01970.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01972.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01982.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01984.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01994.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 01996.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2000 files...
[WARN] 02006.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02008.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02018.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02020.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02030.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02032.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02042.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02044.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02054.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02056.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02066.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02068.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02078.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02080.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02084.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02086.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 02096.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02098.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2100 files...
[WARN] 02108.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02110.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02120.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02122.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02132.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02134.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02136.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02138.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02148.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02150.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02160.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02162.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02172.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02174.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02184.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02186.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02188.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02190.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02200.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02202.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02212.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02214.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02224.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02226.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02236.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02238.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02240.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02242.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02252.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02254.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02264.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02266.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02276.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02278.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02288.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02290.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02292.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02294.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2300 files...
[WARN] 02304.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02306.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02308.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02310.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02320.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02322.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02324.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02326.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02336.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02338.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02340.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02342.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02352.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02354.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02364.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02366.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02376.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02378.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02388.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02390.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02392.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02394.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2400 files...
[WARN] 02404.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02406.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02408.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02410.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02414.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02416.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 02426.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02428.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02438.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02440.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02450.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02452.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02462.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02464.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02466.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02468.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02478.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02480.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02490.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02492.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2500 files...
[WARN] 02502.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02504.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02514.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02516.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02518.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02520.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 02526.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02528.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02538.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02540.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02550.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02552.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02562.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02564.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02574.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02576.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02578.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02580.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02590.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02592.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2600 files...
[WARN] 02602.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02604.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02614.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02616.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02626.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02628.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02638.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02640.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02650.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02652.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02662.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02664.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02674.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02676.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02686.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02688.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02692.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02694.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2700 files...
[WARN] 02704.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02706.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02716.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02718.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02728.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02730.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02740.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02742.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02744.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02746.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02756.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02758.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02768.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02770.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02780.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02782.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02792.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02794.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02796.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02798.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2800 files...
[WARN] 02808.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02810.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02820.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02822.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02832.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02834.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02844.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02846.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02848.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02850.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02860.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02862.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02872.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02874.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02884.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02886.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02896.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02898.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02899.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 2900 files...
[WARN] 02909.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02911.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02921.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02923.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02933.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02935.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02945.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02947.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02957.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02959.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02969.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02971.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02981.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02983.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02993.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02995.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 02998.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3000 files...
[WARN] 03008.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03010.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03020.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03022.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03032.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03034.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03044.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03046.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03048.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03050.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03060.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03062.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03072.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03074.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03084.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03086.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03096.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03098.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03100.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03102.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03112.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03114.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03124.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03126.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03136.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03138.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03148.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03150.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03159.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03161.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03171.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03173.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03175.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03177.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03186.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03188.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03190.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03192.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3200 files...
[WARN] 03202.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03204.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03206.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03208.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03218.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03220.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03221.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03223.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03233.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03235.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03237.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03240.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03250.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03252.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03262.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03264.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03274.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03276.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03286.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03288.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03290.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03292.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3300 files...
[WARN] 03302.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03304.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03314.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03316.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03326.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03328.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03338.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03340.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03342.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03344.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03353.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03363.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03365.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03375.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03377.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03387.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03389.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03399.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3400 files...
[WARN] 03401.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03403.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03405.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03415.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03417.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03427.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03429.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03439.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03441.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03451.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03453.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03455.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03457.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03467.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03469.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03479.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03481.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03491.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03493.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3500 files...
[WARN] 03503.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03505.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03515.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03517.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03527.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03529.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03539.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03541.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03551.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03553.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03563.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03565.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03567.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03569.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03579.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03581.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03591.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03593.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3600 files...
[WARN] 03603.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03605.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03615.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03617.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03619.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03621.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 03627.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03629.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03639.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03641.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03651.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03653.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03663.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03665.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03675.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03677.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03679.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03681.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03691.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03693.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3700 files...
[WARN] 03703.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03705.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03715.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03717.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03727.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03729.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03739.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03741.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03751.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03753.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03763.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03765.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03775.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03777.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03787.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03789.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03793.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03795.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3800 files...
[WARN] 03805.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03807.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03817.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03819.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03829.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03831.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03841.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03843.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03845.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03847.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03857.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03859.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03869.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03871.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03881.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03883.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03893.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03895.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03897.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03899.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 3900 files...
[WARN] 03909.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03911.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03921.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03923.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03933.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03935.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03945.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03947.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03949.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03951.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03961.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03963.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03973.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03975.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03985.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03987.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03997.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 03999.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04000.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04002.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04012.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04014.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04016.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04018.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04027.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04029.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04031.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04033.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04043.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04045.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04047.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04049.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04059.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04061.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04062.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04064.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04074.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04076.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04078.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04080.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04082.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04092.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04094.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04096.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04098.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4100 files...
[WARN] 04107.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04109.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04111.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04113.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04123.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04125.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04127.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04129.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04139.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04141.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04142.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04144.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04154.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04156.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04158.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04160.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04170.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04172.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04182.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04184.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04194.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04196.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4200 files...
[WARN] 04206.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04208.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04218.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04220.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04230.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04232.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04242.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04244.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04254.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04256.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04258.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04260.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04268.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04270.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04280.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04282.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04292.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04294.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4300 files...
[WARN] 04304.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04306.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04316.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04318.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04320.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04322.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04330.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04332.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04342.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04344.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04354.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04356.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04366.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04368.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04378.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04380.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04382.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04384.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04392.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04394.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4400 files...
[WARN] 04404.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04406.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04416.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04418.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04428.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04430.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04440.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04442.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04444.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04446.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04454.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04456.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04466.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04468.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 04478.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04480.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04490.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04492.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4500 files...
[WARN] 04502.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04504.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04545.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04547.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04549.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04551.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04553.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04555.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04557.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04559.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04561.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04563.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04565.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04567.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04569.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04571.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04573.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04575.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04577.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04579.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04581.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04583.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04585.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04587.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04591.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04593.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04595.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04597.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04599.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4600 files...
[WARN] 04601.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04603.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04605.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04607.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04609.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04611.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04613.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04615.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04617.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04619.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04621.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04623.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04625.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04627.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04629.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04631.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04633.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04635.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04637.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04641.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04643.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04645.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04647.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04649.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04651.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04655.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04657.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04659.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04661.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04663.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04665.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04667.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04669.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04671.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04673.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04675.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04677.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04679.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04681.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04683.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04685.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04687.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04689.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04691.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04693.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04695.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04697.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04699.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4700 files...
[WARN] 04701.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04703.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04705.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04707.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04709.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04711.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04713.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04715.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04717.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04721.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04723.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04725.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04727.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04729.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04731.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04733.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04735.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04737.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04739.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04741.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04743.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04745.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04747.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04749.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04751.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04753.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04755.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04757.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04759.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04761.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04763.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04765.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04767.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04771.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04773.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04775.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04777.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04779.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04781.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04783.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04785.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04787.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04789.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04791.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04793.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04795.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04797.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04799.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 4800 files...
[WARN] 04801.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04803.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04805.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04807.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04809.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04811.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04813.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04815.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04816.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04818.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04821.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04823.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04825.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04827.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04829.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04831.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04833.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04835.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04837.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04839.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04841.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04843.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04845.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04847.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04849.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04851.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04853.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04855.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04857.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04859.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04861.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04863.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04865.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04867.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04869.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04872.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04874.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04876.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04878.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04880.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04882.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04884.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04886.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04888.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04890.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04892.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04894.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04896.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04898.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04900.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04902.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04904.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04906.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04908.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04910.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04912.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04914.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04916.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04918.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04920.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04922.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04924.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04926.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04928.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04930.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04932.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04934.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 04938.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/tmp/ipykernel_48/336789165.py:45: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06478.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06489.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06491.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 6500 files...
[WARN] 06501.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06503.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06513.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06515.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06525.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06527.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06538.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06548.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06550.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06560.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06562.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06573.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06583.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06585.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06595.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06597.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 6600 files...
[WARN] 06607.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06609.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06620.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06630.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06632.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06642.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06644.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06655.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06665.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06667.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06673.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06675.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06685.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06687.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06697.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06699.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 6700 files...

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06709.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06711.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06721.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06723.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06725.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06727.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06737.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06739.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06749.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06751.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06761.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06763.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06773.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06775.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06777.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06779.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06789.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06791.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 6800 files...
[WARN] 06801.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06803.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06810.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06812.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06822.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06824.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06834.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06836.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06846.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06848.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06858.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06860.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06862.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06864.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06874.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06876.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06886.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06888.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06898.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06900.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06910.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06912.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06914.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06916.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06926.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06928.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06938.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06940.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06950.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06952.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06962.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06964.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06974.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06976.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06978.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06980.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 06990.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 06992.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 7000 files...
[WARN] 07002.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07004.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07014.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07016.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07026.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07028.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07030.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07032.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07042.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07044.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07054.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07056.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07063.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07065.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07075.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07077.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07087.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07089.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07099.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 7100 files...
[WARN] 07101.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07111.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07113.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07115.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07117.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07127.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07129.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)

[WARN] 07139.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07141.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07151.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07153.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07163.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07165.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07167.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07169.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07179.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07181.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07191.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07193.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 7200 files...
[WARN] 07203.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07205.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07215.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07217.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)

[WARN] 07227.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07229.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07231.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07233.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07243.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07245.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07255.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07257.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07267.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07269.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07279.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07281.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07283.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07285.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07295.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07297.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 7300 files...

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07307.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07309.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07315.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07317.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07327.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07329.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07339.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07341.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07351.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07353.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07363.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07365.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07367.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07369.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07379.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07381.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07391.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07393.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 7400 files...
[WARN] 07403.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07405.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07415.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07417.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07419.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07421.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07431.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07433.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07443.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07445.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07455.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07457.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07467.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07469.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07479.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07481.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07483.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07485.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07495.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07497.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Processed 7500 files...

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07507.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07509.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07519.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07521.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07531.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07533.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07535.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07537.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

[WARN] 07547.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07549.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07559.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
[WARN] 07561.csv: missing required columns ['Time', 'Current_measured', 'Voltage_measured'], skipping.
Done. All CSVs with SoC are in: /kaggle/working/data_with_soc

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

In [6]:
import os
import numpy as np
import pandas as pd


def compute_soc_for_cycle(
    df: pd.DataFrame,
    op_type: str,
    time_col: str = "Time",
    current_col: str = "Current_measured",
    current_noise_threshold: float = 1e-3,
    known_capacity_Ah: float = None,
):
    """
    Compute State of Charge (SoC) for a single cycle, depending on operation type.

    op_type:
      - "discharge": SoC goes from ~1 -> 0 using discharge current
      - "charge"   : SoC goes from ~0 -> 1 using charge current
      - "impedance": no time-series current; returns SoC = NaN for all rows

    For charge / discharge:
      - Uses coulomb counting: I * dt / 3600 [Ah]
      - If known_capacity_Ah is None, capacity is estimated from the cycle itself
        (sum of Ah over the active sign).

    Returns:
      df_out: original df + added columns:
          - delta_t      : time step (s)
          - I_clean      : denoised current
          - SoC          : [0, 1]
          - SoC_percent  : [0, 100]
      capacity_Ah: capacity used for normalization
    """
    op_type = str(op_type).lower()

    # -----------------------------
    # Impedance: no waveform -> NaN SoC
    # -----------------------------
    if op_type == "impedance":
        df = df.copy()
        df["SoC"] = np.nan
        df["SoC_percent"] = np.nan
        return df, np.nan

    # -----------------------------
    # Charge / Discharge
    # -----------------------------
    df = df.copy()
    df = df.sort_values(time_col).reset_index(drop=True)

    # 1) Time step
    df["delta_t"] = df[time_col].diff().fillna(0.0)  # seconds

    # 2) Clean current (remove tiny noise)
    I = df[current_col].astype(float).values
    I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
    df["I_clean"] = I_clean

    # Prepare arrays for integration
    dt = df["delta_t"].values

    if op_type == "discharge":
        # Negative current = discharge
        I_dis = np.clip(I_clean, None, 0.0)  # <= 0
        delta_Ah_dis = -I_dis * dt / 3600.0   # positive Ah
        df["delta_Ah_dis"] = delta_Ah_dis

        # Estimate capacity if not given
        if known_capacity_Ah is None:
            capacity_Ah = delta_Ah_dis.sum()
        else:
            capacity_Ah = float(known_capacity_Ah)

        if capacity_Ah <= 0:
            # Fallback to avoid division by zero
            df["SoC"] = np.nan
            df["SoC_percent"] = np.nan
            return df, np.nan

        df["cum_Ah_dis"] = delta_Ah_dis.cumsum()
        # SoC ~ 1 at start, 0 at end of full discharge
        df["SoC"] = 1.0 - df["cum_Ah_dis"] / capacity_Ah

    elif op_type == "charge":
        # Positive current = charge
        I_chg = np.clip(I_clean, 0.0, None)  # >= 0
        delta_Ah_chg = I_chg * dt / 3600.0   # positive Ah
        df["delta_Ah_chg"] = delta_Ah_chg

        # Estimate capacity if not given
        if known_capacity_Ah is None:
            capacity_Ah = delta_Ah_chg.sum()
        else:
            capacity_Ah = float(known_capacity_Ah)

        if capacity_Ah <= 0:
            # Fallback to avoid division by zero
            df["SoC"] = np.nan
            df["SoC_percent"] = np.nan
            return df, np.nan

        df["cum_Ah_chg"] = delta_Ah_chg.cumsum()
        # SoC ~ 0 at start, 1 at end of full charge
        df["SoC"] = df["cum_Ah_chg"] / capacity_Ah

    else:
        # Unknown type -> no SoC
        df["SoC"] = np.nan
        df["SoC_percent"] = np.nan
        return df, np.nan

    # Clip numerical noise
    df["SoC"] = df["SoC"].clip(0.0, 1.0)
    df["SoC_percent"] = df["SoC"] * 100.0

    return df, capacity_Ah

In [7]:
import os
import pandas as pd

# ---------- Paths: adjust for your environment ----------
METADATA_PATH = "/kaggle/input/nasa-battery-dataset/cleaned_dataset/metadata.csv"
DATA_DIR      = "/kaggle/input/nasa-battery-dataset/cleaned_dataset/data"
OUTPUT_DIR    = "/kaggle/working/data_with_soc_all_types"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load metadata so we know operation type + filename
meta = pd.read_csv(METADATA_PATH)

# Ensure columns exist
if "filename" not in meta.columns or "type" not in meta.columns:
    raise ValueError("metadata.csv must contain 'filename' and 'type' columns.")

meta["filename"] = meta["filename"].astype(str)
meta["type"] = meta["type"].astype(str)

for i, row in meta.iterrows():
    fname = row["filename"]
    op_type = row["type"]  # "charge", "discharge", or "impedance"

    in_path = os.path.join(DATA_DIR, fname)
    out_path = os.path.join(OUTPUT_DIR, fname)

    if not os.path.isfile(in_path):
        print(f"[WARN] {fname}: file not found, skipping.")
        continue

    try:
        df = pd.read_csv(in_path)
    except Exception as e:
        print(f"[WARN] {fname}: error reading file ({e}), skipping.")
        continue

    # For charge/discharge we need Time + Current_measured
    if op_type.lower() in ["charge", "discharge"]:
        required_cols = ["Time", "Current_measured"]
        if not all(c in df.columns for c in required_cols):
            print(f"[WARN] {fname}: missing {required_cols}, cannot compute SoC, skipping.")
            continue

        df_soc, cap_Ah = compute_soc_for_cycle(
            df,
            op_type=op_type,
            time_col="Time",
            current_col="Current_measured",
            # known_capacity_Ah=2.0  # <- uncomment to force rated capacity
        )

    else:
        # Impedance: no waveform; function will create NaN SoC
        df_soc, cap_Ah = compute_soc_for_cycle(df, op_type=op_type)

    # Save with SoC column
    df_soc.to_csv(out_path, index=False)

    if (i + 1) % 100 == 0:
        print(f"Processed {i + 1} / {len(meta)} files...")

print("Done. Files with SoC are in:", OUTPUT_DIR)

Processed 100 / 7565 files...
Processed 200 / 7565 files...
Processed 300 / 7565 files...
Processed 400 / 7565 files...
Processed 500 / 7565 files...
Processed 600 / 7565 files...
Processed 700 / 7565 files...
Processed 800 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 900 / 7565 files...
Processed 1000 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1100 / 7565 files...
Processed 1200 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1300 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1400 / 7565 files...
Processed 1500 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1600 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1700 / 7565 files...
Processed 1800 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 1900 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2000 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2100 / 7565 files...
Processed 2200 / 7565 files...
Processed 2300 / 7565 files...
Processed 2400 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2500 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2600 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 2700 / 7565 files...
Processed 2800 / 7565 files...
Processed 2900 / 7565 files...
Processed 3000 / 7565 files...
Processed 3100 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3200 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3300 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3400 / 7565 files...
Processed 3500 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3600 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3700 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 3800 / 7565 files...
Processed 3900 / 7565 files...
Processed 4000 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4100 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4200 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4300 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4400 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 4500 / 7565 files...
Processed 4600 / 7565 files...
Processed 4700 / 7565 files...
Processed 4800 / 7565 files...
Processed 4900 / 7565 files...
Processed 5000 / 7565 files...
Processed 5100 / 7565 files...
Processed 5200 / 7565 files...
Processed 5300 / 7565 files...
Processed 5400 / 7565 files...
Processed 5500 / 7565 files...
Processed 5600 / 7565 files...
Processed 5700 / 7565 files...
Processed 5800 / 7565 files...
Processed 5900 / 7565 files...
Processed 6000 / 7565 files...
Processed 6100 / 7565 files...
Processed 6200 / 7565 files...
Processed 6300 / 7565 files...
Processed 6400 / 7565 files...

/tmp/ipykernel_48/4126542930.py:57: RuntimeWarning: invalid value encountered in less
  I_clean = np.where(np.abs(I) < current_noise_threshold, 0.0, I)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

Processed 6500 / 7565 files...
Processed 6600 / 7565 files...
Processed 6700 / 7565 files...
Processed 6800 / 7565 files...
Processed 6900 / 7565 files...
Processed 7000 / 7565 files...
Processed 7100 / 7565 files...
Processed 7200 / 7565 files...
Processed 7300 / 7565 files...
Processed 7400 / 7565 files...
Processed 7500 / 7565 files...
Done. Files with SoC are in: /kaggle/working/data_with_soc_all_types

In [9]:
df2 = pd.read_csv("/kaggle/working/data_with_soc_all_types/00001.csv")
df2

,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time,delta_t,I_clean,delta_Ah_dis,cum_Ah_dis,SoC,SoC_percent
0,4.246711,0.000252,6.212696,0.0002,0.000,0.000,0.000,0.000000,-0.000000,-0.000000,1.000000,100.000000
1,4.246764,-0.001411,6.234019,0.0002,4.262,9.360,9.360,-0.001411,0.000004,0.000004,0.999998,99.999785
2,4.039277,-0.995093,6.250255,1.0000,3.465,23.281,13.921,-0.995093,0.003848,0.003852,0.997742,99.774227
3,4.019506,-0.996731,6.302176,1.0000,3.451,36.406,13.125,-0.996731,0.003634,0.007486,0.995612,99.561216
4,4.004763,-0.992845,6.361645,1.0000,3.438,49.625,13.219,-0.992845,0.003646,0.011131,0.993475,99.347516
...,...,...,...,...,...,...,...,...,...,...,...,...
485,3.303251,-0.001760,9.662331,0.0004,0.000,6382.063,13.641,-0.001760,0.000007,1.705952,0.000015,0.001528
486,3.310303,-0.000756,9.390489,0.0002,0.000,6395.547,13.484,0.000000,-0.000000,1.705952,0.000015,0.001528
487,3.317351,-0.003318,9.137008,0.0002,0.000,6409.063,13.516,-0.003318,0.000012,1.705964,0.000008,0.000798
488,3.323387,-0.002291,8.972806,0.0002,0.000,6422.625,13.562,-0.002291,0.000009,1.705973,0.000003,0.000292
489,3.329356,-0.001326,8.756381,0.0002,0.000,6436.141,13.516,-0.001326,0.000005,1.705978,0.000000,0.000000

In [10]:
import pandas as pd
import numpy as np
import os

# ======================================================
# Paths (adjust to your environment)
# ======================================================
METADATA_PATH = "/kaggle/input/nasa-battery-dataset/cleaned_dataset/metadata.csv"
SAVE_PATH     = "/kaggle/working/metadata_with_cycles.csv"

# ======================================================
# Load metadata
# Expected columns: type, start_time, ambient_temperature,
#                   battery_id, test_id, uid, filename, Capacity, Re, Rct, ...
# ======================================================
meta = pd.read_csv(METADATA_PATH)

# Basic sanity checks
required_cols = ["battery_id", "type", "start_time", "filename"]
missing = [c for c in required_cols if c not in meta.columns]
if missing:
    raise ValueError(f"metadata.csv is missing columns: {missing}")

# ------------------------------------------------------
# 1) Parse start_time as datetime (if possible)
#    If it’s already numeric (e.g., MATLAB datenum converted), this will still try.
# ------------------------------------------------------
meta["start_time_parsed"] = pd.to_datetime(meta["start_time"], errors="coerce")

# If some times are NaT, we still want deterministic ordering.
# We’ll sort using parsed time first, then fallback to original index.
meta["_orig_idx"] = np.arange(len(meta))

meta = meta.sort_values(
    by=["battery_id", "start_time_parsed", "_orig_idx"]
).reset_index(drop=True)

# ------------------------------------------------------
# 2) Global cycle number per battery
#    => For each battery_id, 1..N in chronological order
# ------------------------------------------------------
meta["cycle_number"] = meta.groupby("battery_id").cumcount() + 1

# ------------------------------------------------------
# 3) Cycle number per battery AND operation type
#    => For each battery_id & type (charge/discharge/impedance), 1..N
# ------------------------------------------------------
meta["cycle_number_by_type"] = meta.groupby(["battery_id", "type"]).cumcount() + 1

# (Optional) If you want separate columns for each type, you can pivot later.
# For now we keep one generic column.

# ------------------------------------------------------
# 4) Save updated metadata
# ------------------------------------------------------
# Drop helper columns if you don't want them
meta = meta.drop(columns=["start_time_parsed", "_orig_idx"])

meta.to_csv(SAVE_PATH, index=False)
print(f"Saved metadata with cycle_number columns to: {SAVE_PATH}")

# Quick peek
print(
    meta[
        [
            "battery_id",
            "type",
            "start_time",
            "filename",
            "cycle_number",
            "cycle_number_by_type",
        ]
    ]
    .head(20)
)

/tmp/ipykernel_48/2077354883.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  meta["start_time_parsed"] = pd.to_datetime(meta["start_time"], errors="coerce")

Saved metadata with cycle_number columns to: /kaggle/working/metadata_with_cycles.csv
   battery_id       type                                         start_time  \
0       B0005     charge  [2.0080e+03 4.0000e+00 2.0000e+00 1.3000e+01 8...
1       B0005  discharge  [2.0080e+03 4.0000e+00 2.0000e+00 1.5000e+01 2...
2       B0005     charge  [2.0080e+03 4.0000e+00 2.0000e+00 1.6000e+01 3...
3       B0005  discharge  [2.0080e+03 4.0000e+00 2.0000e+00 1.9000e+01 4...
4       B0005     charge  [2.0080e+03 4.0000e+00 2.0000e+00 2.0000e+01 5...
5       B0005  discharge  [2.008e+03 4.000e+00 3.000e+00 0.000e+00 1.000...
6       B0005     charge  [2.0080e+03 4.0000e+00 3.0000e+00 1.0000e+00 1...
7       B0005  discharge  [2008.       4.       3.       4.      16.    ...
8       B0005     charge  [2008.       4.       3.       5.      27.    ...
9       B0005  discharge  [2008.       4.       3.       8.      33.    ...
10      B0005     charge  [2008.       4.       3.       9.      44.    ...
11      B0005  discharge  [2008.       4.       3.      12.      55.    ...
12      B0005     charge  [2008.       4.       3.      14.       6.    ...
13      B0005  discharge  [2008.       4.       3.      17.      17.    ...
14      B0005     charge  [2008.       4.       3.      18.      28.    ...
15      B0005  discharge  [2008.       4.       3.      21.      28.    ...
16      B0005     charge  [2008.       4.       3.      22.      38.    ...
17      B0005  discharge  [2.0080e+03 4.0000e+00 4.0000e+00 1.0000e+00 3...
18      B0005     charge  [2.008e+03 4.000e+00 4.000e+00 2.000e+00 4.800...
19      B0005  discharge  [2008.       4.       4.       5.      48.    ...

     filename  cycle_number  cycle_number_by_type
0   05121.csv             1                     1
1   05122.csv             2                     1
2   05123.csv             3                     2
3   05124.csv             4                     2
4   05125.csv             5                     3
5   05126.csv             6                     3
6   05127.csv             7                     4
7   05128.csv             8                     4
8   05129.csv             9                     5
9   05130.csv            10                     5
10  05131.csv            11                     6
11  05132.csv            12                     6
12  05133.csv            13                     7
13  05134.csv            14                     7
14  05135.csv            15                     8
15  05136.csv            16                     8
16  05137.csv            17                     9
17  05138.csv            18                     9
18  05139.csv            19                    10
19  05140.csv            20                    10

In [11]:
import numpy as np
import pandas as pd
from sklearn.isotonic import IsotonicRegression


def compute_soh_advanced(
    metadata: pd.DataFrame,
    rated_capacity_ah: float = 2.0,
    capacity_col: str = "Capacity",
    re_col: str = "Re",
    rct_col: str = "Rct",
) -> pd.DataFrame:
    """
    Compute an advanced SoH estimate for each row in metadata by combining:
      - Capacity-based SoH (primary, from discharge cycles)
      - BMS discharge capacity (backup when Capacity missing)
      - Impedance features (Re, Rct) normalized to early-life values
      - Monotonic smoothing per battery vs cycle_number (SoH must not increase)

    Requirements in metadata:
      - 'battery_id'
      - 'cycle_number' (global cycle index per battery)
      - 'type' (e.g. 'charge', 'discharge', 'impedance')
      - Optional:
          - capacity_col (e.g. 'Capacity')
          - 'bms_disc_capacity_ah'
          - re_col (e.g. 'Re')
          - rct_col (e.g. 'Rct')

    Returns:
      metadata_copy: same as input but with new columns:
        - 'soh_cap_raw'
        - 'soh_re_raw'
        - 'soh_rct_raw'
        - 'soh_eis_raw'
        - 'SoH'  (final smoothed SoH in [0, ~1])
    """

    df = metadata.copy()

    # ---------------------------------------------------------------------
    # 0) Sanity checks
    # ---------------------------------------------------------------------
    for col in ["battery_id", "cycle_number", "type"]:
        if col not in df.columns:
            raise ValueError(f"metadata must contain '{col}' column")

    df["type"] = df["type"].astype(str).str.lower()

    # ---------------------------------------------------------------------
    # 1) Capacity-based SoH (primary signal)
    # ---------------------------------------------------------------------
    cap_series = pd.to_numeric(df.get(capacity_col, np.nan), errors="coerce")
    df["soh_cap_raw"] = cap_series / rated_capacity_ah

    # Use BMS discharge capacity as backup for discharge cycles
    if "bms_disc_capacity_ah" in df.columns:
        bms_cap = pd.to_numeric(df["bms_disc_capacity_ah"], errors="coerce")
        mask_no_cap = df["soh_cap_raw"].isna() & df["type"].eq("discharge")
        df.loc[mask_no_cap, "soh_cap_raw"] = bms_cap[mask_no_cap] / rated_capacity_ah

    # ---------------------------------------------------------------------
    # 2) Resistance-based SoH (from Re / Rct), normalized to early-life
    # ---------------------------------------------------------------------
    # Initialize columns
    df["soh_re_raw"] = np.nan
    df["soh_rct_raw"] = np.nan

    has_re = re_col in df.columns
    has_rct = rct_col in df.columns

    if has_re:
        df[re_col] = pd.to_numeric(df[re_col], errors="coerce")
    if has_rct:
        df[rct_col] = pd.to_numeric(df[rct_col], errors="coerce")

    # Compute per-battery baselines and normalized SoH-like signals
    for bid, sub_idx in df.groupby("battery_id").groups.items():
        sub = df.loc[sub_idx]

        # Early-life baseline from first few impedance cycles
        if has_re:
            re_vals = sub[re_col].dropna()
            if not re_vals.empty:
                # baseline ~ median of first 3 valid values
                baseline_Re = re_vals.iloc[:3].median()
                # soh_re_raw = baseline_Re / Re  (higher Re => lower SoH)
                re_norm = baseline_Re / sub[re_col]
                df.loc[sub_idx, "soh_re_raw"] = re_norm.replace([np.inf, -np.inf], np.nan)

        if has_rct:
            rct_vals = sub[rct_col].dropna()
            if not rct_vals.empty:
                baseline_Rct = rct_vals.iloc[:3].median()
                rct_norm = baseline_Rct / sub[rct_col]
                df.loc[sub_idx, "soh_rct_raw"] = rct_norm.replace([np.inf, -np.inf], np.nan)

    # Combine impedance-based SoH when both or one are available
    df["soh_eis_raw"] = np.nan
    if has_re or has_rct:
        if has_re and has_rct:
            df["soh_eis_raw"] = np.nanmean(
                np.vstack([df["soh_re_raw"], df["soh_rct_raw"]]), axis=0
            )
        elif has_re:
            df["soh_eis_raw"] = df["soh_re_raw"]
        elif has_rct:
            df["soh_eis_raw"] = df["soh_rct_raw"]

    # Clip raw impedance SoH to a reasonable range
    df["soh_eis_raw"] = df["soh_eis_raw"].clip(lower=0.0, upper=1.5)

    # ---------------------------------------------------------------------
    # 3) Combine capacity + impedance into a single noisy SoH signal
    # ---------------------------------------------------------------------
    # Priority: capacity > BMS > impedance
    # We already used BMS to fill soh_cap_raw, so now:
    #   - if soh_cap_raw exists, use it (strongest)
    #   - else if soh_eis_raw exists, use that
    #   - else NaN (no signal)
    df["soh_signal"] = df["soh_cap_raw"]
    mask_no_cap_signal = df["soh_signal"].isna() & df["soh_eis_raw"].notna()
    df.loc[mask_no_cap_signal, "soh_signal"] = df.loc[mask_no_cap_signal, "soh_eis_raw"]

    # ---------------------------------------------------------------------
    # 4) Monotonic smoothing per battery vs cycle_number
    #    SoH should *not increase* with cycle_number.
    #    Use isotonic regression (increasing=False) per battery.
    # ---------------------------------------------------------------------
    df["SoH"] = np.nan

    for bid, sub_idx in df.groupby("battery_id").groups.items():
        sub = df.loc[sub_idx].sort_values("cycle_number")

        x = sub["cycle_number"].values.astype(float)
        y = sub["soh_signal"].values.astype(float)
        mask_valid = ~np.isnan(y)

        if mask_valid.sum() == 0:
            # No SoH info at all for this battery
            continue
        elif mask_valid.sum() == 1:
            # Only one labeled point: propagate that SoH to all cycles
            soh_single = y[mask_valid][0]
            df.loc[sub.index, "SoH"] = soh_single
        else:
            # Fit monotone *decreasing* curve
            ir = IsotonicRegression(increasing=False, out_of_bounds="clip")
            ir.fit(x[mask_valid], y[mask_valid])
            soh_smooth = ir.predict(x)
            df.loc[sub.index, "SoH"] = soh_smooth

    # Final clipping: SoH in [0, 1.2] (allow slight >1 due to noise)
    df["SoH"] = df["SoH"].clip(lower=0.0, upper=1.2)

    return df

In [12]:
# 1) Load your metadata that already has cycle_number etc.
meta = pd.read_csv("/kaggle/working/metadata_with_cycles.csv")

# 2) Compute advanced SoH
meta_soh = compute_soh_advanced(meta, rated_capacity_ah=2.0)

# 3) Save
meta_soh.to_csv("/kaggle/working/metadata_with_soh_advanced.csv", index=False)

print(meta_soh[["battery_id", "type", "cycle_number", "Capacity", "Re", "Rct", "SoH"]].head(30))

   battery_id       type  cycle_number            Capacity  Re  Rct       SoH
0       B0005     charge             1                 NaN NaN  NaN  0.946806
1       B0005  discharge             2  1.8564874208181574 NaN  NaN  0.946806
2       B0005     charge             3                 NaN NaN  NaN  0.946806
3       B0005  discharge             4   1.846327249719927 NaN  NaN  0.946806
4       B0005     charge             5                 NaN NaN  NaN  0.946806
5       B0005  discharge             6  1.8353491942234077 NaN  NaN  0.946806
6       B0005     charge             7                 NaN NaN  NaN  0.946806
7       B0005  discharge             8  1.8352625275821128 NaN  NaN  0.946806
8       B0005     charge             9                 NaN NaN  NaN  0.946806
9       B0005  discharge            10  1.8346455082120419 NaN  NaN  0.946806
10      B0005     charge            11                 NaN NaN  NaN  0.946806
11      B0005  discharge            12  1.8356616600675495 NaN  NaN  0.946806
12      B0005     charge            13                 NaN NaN  NaN  0.946806
13      B0005  discharge            14  1.8351461429226603 NaN  NaN  0.946806
14      B0005     charge            15                 NaN NaN  NaN  0.946806
15      B0005  discharge            16  1.8257567905665537 NaN  NaN  0.946806
16      B0005     charge            17                 NaN NaN  NaN  0.946806
17      B0005  discharge            18  1.8247738529891333 NaN  NaN  0.946806
18      B0005     charge            19                 NaN NaN  NaN  0.946806
19      B0005  discharge            20   1.824613268496936 NaN  NaN  0.946806
20      B0005     charge            21                 NaN NaN  NaN  0.946806
21      B0005  discharge            22  1.8246195526864504 NaN  NaN  0.946806
22      B0005     charge            23                 NaN NaN  NaN  0.946806
23      B0005     charge            24                 NaN NaN  NaN  0.946806
24      B0005  discharge            25  1.8142019357673917 NaN  NaN  0.946806
25      B0005     charge            26                 NaN NaN  NaN  0.946806
26      B0005  discharge            27  1.8137521577549054 NaN  NaN  0.946806
27      B0005     charge            28                 NaN NaN  NaN  0.946806
28      B0005  discharge            29  1.8134404914735822 NaN  NaN  0.946806
29      B0005     charge            30                 NaN NaN  NaN  0.946806

/tmp/ipykernel_48/4035467779.py:102: RuntimeWarning: Mean of empty slice
  df["soh_eis_raw"] = np.nanmean(
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()